/* (c) 2013 Nathanael Schilling
 * This file includes functions for easy manipulation of the metadata files
 * generated by ngram.counting
 */
#ifndef NGRAM_ANALYIS_METADATA_MANAGEMENT_H
#define NGRAM_ANALYIS_METADATA_MANAGEMENT_H

#include <vector>
#include <string>
#include <sstream>
#include <fstream>
#include <iostream>
#include <string.h>

using namespace std;
class Metadata
{
	public:
		Metadata(){};//Do not use
		Metadata(string filename);
		void write();

		vector<vector<unsigned int> > indices;
		unsigned long long num_words;
		unsigned int time_taken;
		unsigned int max_frequency;
		string file_name;
};


#endif
