/* (c) 2013 Nathanael Schilling
 * This file includes functions for easy manipulation of the metadata files
 * generated by ngram.counting
 */
#ifndef NGRAM_ANALYIS_METADATA_MANAGEMENT_H
#define NGRAM_ANALYIS_METADATA_MANAGEMENT_H

#include <set>
#include <vector>
#include <string>
#include <sstream>
#include <fstream>
#include <iostream>
#include <string.h>
#include <algorithm>

#include "config.h"

using namespace std;
class Metadata
{
	public:
		Metadata(){};//Do not use
		Metadata(string &filename,string &foldername,bool fileMayNotExist);
		void write();


		string file_name;
		long long num_words;
		int time_taken;
		int max_word_size;
		int max_classification_size;
		int max_lemma_size;
		set<vector<unsigned int> > indices;
		bool posIndexesExist;
		bool isPos;


		set<vector<unsigned int> > inverted_indices;
		bool wordlength_stats_exist;
		unsigned int max_frequency;
		string folder_name;
		string metadata_filename;


		bool fileExistsAlready;
};


#endif
